name: terrariacontrolpanel
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^1.1.0
  http: ^0.12.1


flutter:
  uses-material-design: true
